spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: ${PROD_DB_DRIVER_NAME}

  jpa:
    properties.hibernate.default_schema: ${PROD_DB_DEFAULT_SCHEMA}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate # DB - Spring Entity 유효성 체크

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access.expiration: ${JWT_ACCESS_EXPIRATION}
  refresh.expiration: ${JWT_REFRESH_EXPIRATION}
