spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:heygongc;MODE=PostgreSQL;NON_KEYWORDS=MEMBER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

google:
  client:
    id: 753695021159-ef799dfi6q7bpodifg41khuomc1r80km.apps.googlemembercontent.com
    secret: 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
    redirect-uri: http://localhost:8080/v1/members/login/google/callback
