create table IF NOT EXISTS device (
        battery integer,
        is_paired boolean default false not null,
        sound_active boolean default false not null,
        sound_mode boolean default false not null,
        stream_active boolean default false not null,
        temperature integer,
        created_at timestamp(6) not null,
        device_seq bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_seq bigint,
        camera_mode varchar(255) default 'FRONT' not null check (camera_mode in ('FRONT','BACK')),
        device_id varchar(255) not null,
        device_name varchar(255),
        device_os varchar(255) not null check (device_os in ('AOS','IOS')),
        fcm_token varchar(255),
        model_name varchar(255) not null,
        sensitivity varchar(255) default 'MEDIUM' not null check (sensitivity in ('VERYHIGH','HIGH','MEDIUM','LOW','VERYLOW')),
        primary key (device_seq)
    );
create table IF NOT EXISTS notification (
        created_at timestamp(6) not null,
        device_seq bigint,
        noti_seq bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_seq bigint,
        type varchar(255) not null check (type in ('SOUND','DEVICE')),
        primary key (noti_seq)
    );
create table IF NOT EXISTS user_token (
        user_seq bigint not null,
        refresh_token varchar(255) not null,
        primary key (refresh_token)
    );
create table IF NOT EXISTS users (
        ads boolean not null,
        alarm boolean not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        updated_at timestamp(6) not null,
        user_seq bigint generated by default as identity,
        email varchar(200),
        sns_id varchar(200) not null,
        user_id varchar(200) not null,
        device_id varchar(255) not null,
        device_os varchar(255) not null check (device_os in ('AOS','IOS')),
        fcm_token varchar(255),
        sns_type varchar(255) not null check (sns_type in ('GOOGLE','APPLE')),
        primary key (user_seq)
    );
