create table IF NOT EXISTS videos (
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    user_seq bigint,
    video_seq bigint generated by default as identity,
    name varchar(255) not null,
    url varchar(255) not null,
    primary key (video_seq)
);

ALTER TABLE device RENAME COLUMN is_paired TO is_connected;

